INC=/usr/include


INCLIB=$(INC)/../lib

UNAME := $(shell uname)

CFLAGS= -I$(INC) -O3 -I.. -g

NAME= mlx-test
SRC = main.c
OBJ = $(SRC:%.c=%.o)

LFLAGS = -L.. -lmlx -L$(INCLIB) -lXext -lX11 -lm

ifeq ($(UNAME), Darwin)
	# mac
	cc = clang
else ifeq ($(UNAME), FreeBSD)
	# FreeBSD
	cc = clang
else
	#Linux and others...
	cc	= gcc
	LFLAGS += -lbsd
endif

all: $(NAME)

$(NAME): $(OBJ)
	@$(cc) -o $(NAME) $(OBJ) $(LFLAGS)  > /dev/null 2>&1

show:
	@printf "UNAME		: $(UNAME)\n"
	@printf "NAME  		: $(NAME)\n"
	@printf "cc		: $(cc)\n"
	@printf "CFLAGS		: $(CFLAGS)\n"
	@printf "LFLAGS		: $(LFLAGS)\n"
	@printf "SRC		:\n	$(SRC)\n"
	@printf "OBJ		:\n	$(OBJ)\n"

clean:
	@rm -f $(NAME) $(OBJ) *~ core *.core  > /dev/null 2>&1

re: clean all
